# Generated by Django 4.0.4 on 2022-04-28 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advert',
            options={'verbose_name': 'Объявление', 'verbose_name_plural': 'Объявления'},
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=30, null=True, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='Фото')),
                ('advert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.advert', verbose_name='Объявление')),
            ],
        ),
    ]
