# Generated by Django 4.0.4 on 2022-04-28 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_photo_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='gallery',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.gallery', verbose_name='Галерея'),
            preserve_default=False,
        ),
    ]
