# Generated by Django 4.0.4 on 2022-05-02 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_advert_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.gallery', verbose_name='Галерея'),
        ),
    ]
